# My sway configuration file

bindsym $mod+Shift+Escape  exec loginctl lock-session

include colors
client.focused          $base05 $base0D $base00 $base0D $base0D
client.focused_inactive $base01 $base01 $base05 $base03 $base01
client.unfocused        $base01 $base00 $base05 $base01 $base01
client.urgent           $base08 $base08 $base00 $base08 $base08
client.placeholder      $base00 $base00 $base05 $base00 $base00
client.background       $base07

font pango: JetBrains Mono Bold 9
output * bg ~/Pictures/mojave.jpg fill

input "type:touchpad" {
    natural_scroll enabled
}

input "type:keyboard" {
    xkb_layout "gb" 
}


