# My sway configuration file

bindsym $mod+Shift+Escape  exec loginctl lock-session

include colors
client.focused          $base05 $base0D $base00 $base0D $base0D
client.focused_inactive $base01 $base01 $base05 $base03 $base01
client.unfocused        $base01 $base00 $base05 $base01 $base01
client.urgent           $base08 $base08 $base00 $base08 $base08
client.placeholder      $base00 $base00 $base05 $base00 $base00
client.background       $base07

input * {
    xkb_layout "gb" 
}

font pango: JetBrains Mono Bold 9
output * bg ~/Pictures/wave.jpg fill

input "touchpad" {
    natural_scroll false
    click_method button_areas
}

default_border pixel 2
