bindsym {
    Print       exec grim - | tee ~/Pictures/Screenshots/screenshot_screen$(date +'%y-%m-%d_%H-%M-%S').png | wl-copy
    Ctrl+Print   exec grim -g "$(slurp)" - | tee ~/Pictures/Screenshots/screenshot_area$(date +'%y-%m-%d_%H-%M-%S').png | wl-copy
}
